import TopMenu from "@/components/ui/top-menu/TopMenu";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Productos",
  description: "Generated by create next app",
};

export default function ShopLayout({
 children
}: {
 children: React.ReactNode;
}) {
  return (
    <main className=" min-h-screen">
      <TopMenu/>
        {children}
    
    </main>
  );
}